// app/constants/index.ts

export const WS_CONFIG = {
  MAX_RECONNECT_ATTEMPTS: 10,
  BASE_RECONNECT_DELAY: 1000,
  MAX_RECONNECT_DELAY: 10000,
  CONNECTION_TIMEOUT: 10000,
  HEARTBEAT_INTERVAL: 15000,
  ARRIVAL_THRESHOLD: 0.1,
  VISIBILITY_RECONNECT_DELAY: 500,
  MESSAGE_RETRY_DELAY: 2000,
} as const;

export const FARE_CONFIG = {
  RATE_PER_KM: 15,
  MIN_FARE: 50,
} as const;

export const RIDE_CONFIG = {
  SEARCH_RADIUS_KM: 5,
  ESTIMATED_WAIT_MIN: 2,
  ESTIMATED_WAIT_MAX: 5,
} as const;